In [17]:
from tensorflow.keras.preprocessing.text import one_hot

In [49]:
# sentences 
sent=[ 'the glass of milk',
       'the glass of juice',
       'the cup of tea',
       'I am a good boy',
       'I am a good developer',
       'Understand the meaning of words',
       'The cup of coffee']

sent_1=[
    'The cup of good developer of words'
]

In [50]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'Understand the meaning of words',
 'The cup of coffee']

In [51]:
## Define the vocabulary size
voc_size=10000

In [52]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size) for words in sent]
one_hot_repr

[[5360, 5755, 8256, 8251],
 [5360, 5755, 8256, 6959],
 [5360, 117, 8256, 1016],
 [7316, 7993, 3253, 7555, 5048],
 [7316, 7993, 3253, 7555, 1499],
 [3931, 5360, 6977, 8256, 6164],
 [5360, 117, 8256, 8050]]

In [57]:
### One Hot Representation
one_hot_repr_1=[one_hot(words,voc_size) for words in sent_1]
one_hot_repr_1

[[5360, 117, 8256, 7555, 1499, 8256, 6164]]

In [58]:
## word embedding Representation

from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences 
# pad_sequences is used to reshape the data(sentence) such that all the sentences have same length -- this is required because the input to the RNN should have fixed size
from tensorflow.keras.models import Sequential

In [59]:
import numpy as np

In [61]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)



[[   0    0    0    0 5360 5755 8256 8251]
 [   0    0    0    0 5360 5755 8256 6959]
 [   0    0    0    0 5360  117 8256 1016]
 [   0    0    0 7316 7993 3253 7555 5048]
 [   0    0    0 7316 7993 3253 7555 1499]
 [   0    0    0 3931 5360 6977 8256 6164]
 [   0    0    0    0 5360  117 8256 8050]]


In [25]:
# featuree representation
dim=10
## dimensions means feature space used to represent the words because each word is represented by a vector of size dim

In [29]:
model = Sequential()
model.add(Embedding(voc_size, dim))
model.compile(optimizer='adam', loss='mse')
model.build(input_shape=(None, sent_length))  # Build the model
model.summary()

Model: "sequential_5"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_5 (Embedding)         │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [28]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 561ms/step


array([[[-0.01352572,  0.01769776, -0.01068873, -0.03918955,
          0.04056981, -0.02238764, -0.03698212, -0.0288271 ,
         -0.0270035 ,  0.04487518],
        [-0.01352572,  0.01769776, -0.01068873, -0.03918955,
          0.04056981, -0.02238764, -0.03698212, -0.0288271 ,
         -0.0270035 ,  0.04487518],
        [-0.01352572,  0.01769776, -0.01068873, -0.03918955,
          0.04056981, -0.02238764, -0.03698212, -0.0288271 ,
         -0.0270035 ,  0.04487518],
        [-0.01352572,  0.01769776, -0.01068873, -0.03918955,
          0.04056981, -0.02238764, -0.03698212, -0.0288271 ,
         -0.0270035 ,  0.04487518],
        [ 0.03424572, -0.02067815,  0.04694477,  0.01388803,
         -0.0022197 , -0.03759515,  0.04421279,  0.04247135,
         -0.00960357,  0.01605428],
        [ 0.00982105, -0.02488172,  0.01646617, -0.01625459,
          0.0184431 , -0.01311358,  0.01027555,  0.01004546,
          0.0247694 , -0.03536625],
        [-0.02589349,  0.0081835 , -0.02174413,  0.0

In [47]:

print(embedded_docs[0])
print('-------------------------------------------')

# Get prediction for 1st sentence
pred = model.predict(embedded_docs[0:1])

print(f"Shape: {pred.shape}")           # (1, 8, 10)
print(f"\nFirst word embedding:\n{pred[0][0]}")   # 10 values for 1st word

[   0    0    0    0 5360 5755 8256 8251]
-------------------------------------------
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step
Shape: (1, 8, 10)

First word embedding:
[ 0.00754174 -0.01855354  0.01093277 -0.01456044 -0.02195813  0.0293708
 -0.00516801 -0.03532672 -0.04611132 -0.02417651]
